name: Rust Beta

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.11'
    - name: Update Rust Beta
      run: |
        rustup update beta
        rustup default beta
    - name: Run tests
      run: cargo test --verbose --features full,apply,fetch,generate,foreach,python,lua
    - name: Run luajit tests separately as its mutually exclusive with lua feature
      run: cargo test luajit --verbose --locked --features=luajit,full
